"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState
} from "react";

export type Language = "en" | "am";

type Dictionary = typeof dictionary.en;
export type TranslationKey = keyof Dictionary;

const storageKey = "qesem-language";

const dictionary = {
  en: {
    "nav.shop": "Shop",
    "nav.custom": "Custom Design",
    "nav.story": "Our Story",
    "nav.how": "How It Works",
    "nav.account": "Account",
    "nav.bag": "Bag",
    "nav.search": "Search",
    "nav.openMenu": "Open menu",
    "nav.closeMenu": "Close menu",
    "language.label": "Language",
    "language.english": "English",
    "language.amharic": "Amharic",
    "hero.aria": "Qesem Habesha Libs homepage introduction",
    "hero.eyebrow": "Modern Habesha fashion, made to order",
    "hero.primary": "Explore designs",
    "hero.secondary": "Create your own",
    "hero.alt": "Editorial Qesem Habesha Libs model wearing an ivory embroidered dress",
    "brand.aria": "Animate Qesem Habesha Libs branding",
    "designs.eyebrow": "Our designs",
    "designs.title": "Pieces we have created before.",
    "designs.viewAll": "View all",
    "custom.eyebrow": "Custom design",
    "custom.title": "Send the design you have in mind.",
    "custom.body":
      "Share a photo or video. We review the garment, fabric direction, and finish, then send your custom price before the next step begins.",
    "custom.cta": "Get my price",
    "custom.alt": "Phone, fabric, trim, and measuring tape for a custom Habesha design",
    "garment.alt": "Product-only Habesha garment preview without a person",
    "garment.hint": "Hover or tap to turn the garment",
    "process.eyebrow": "How it works",
    "process.title": "A considered path from idea to garment.",
    "process.step1": "Choose or send your design",
    "process.step2": "Receive your custom price",
    "process.step3": "Confirm your measurements",
    "process.step4": "We make it and deliver it",
    "craft.eyebrow": "Made with intention",
    "craft.title": "Crafted through Ethiopian tradition, made individually for you.",
    "craft.alt": "Artisan hands arranging embroidered Habesha fabric",
    "measurement.eyebrow": "The perfect fit",
    "measurement.title": "We will show you exactly how to measure from home.",
    "measurement.cta": "Watch the guide",
    "measurement.alt": "Close detail of embroidered fabric used as a measurement guide preview",
    "measurement.preview": "Fit guide preview",
    "final.eyebrow": "Begin",
    "final.line1": "Your design.",
    "final.line2": "Your measurements.",
    "final.line3": "Made for you.",
    "footer.tagline": "Tradition, made yours.",
    "footer.previous": "Previous Designs",
    "footer.measurement": "Measurement Guide",
    "footer.shipping": "Shipping",
    "footer.returns": "Returns",
    "footer.faq": "FAQ",
    "footer.contact": "Contact",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "placeholder.comingSoon": "Coming soon",
    "placeholder.default": "Coming Soon",
    "placeholder.body":
      "This destination is reserved for the next phase. The homepage links are active while the full experience is being designed.",
    "placeholder.return": "Return home",
    "custom.progress.design": "Design",
    "custom.progress.details": "Details",
    "custom.progress.for": "For",
    "custom.progress.measurements": "Measurements",
    "custom.progress.contact": "Contact",
    "custom.progress.review": "Review",
    "custom.progress.aria": "Custom design progress",
    "custom.shell.eyebrow": "Custom design",
    "custom.visual.0.heading": "Create something made for you.",
    "custom.visual.0.copy":
      "Show us what you have in mind, provide your measurements, and we'll send your custom price shortly.",
    "custom.visual.1.heading": "Every detail matters.",
    "custom.visual.1.copy":
      "Color, sleeve shape, neckline, finish and timeline all help us understand the work.",
    "custom.visual.2.heading": "Made for the right person.",
    "custom.visual.2.copy": "A custom garment begins with the recipient, not just the buyer.",
    "custom.visual.3.heading": "Measure with confidence.",
    "custom.visual.3.copy": "The guide highlights each body area as you complete the fit details.",
    "custom.visual.4.heading": "We'll send the price to you.",
    "custom.visual.4.copy": "No account, password, or checkout is needed at this stage.",
    "custom.visual.5.heading": "One last look.",
    "custom.visual.5.copy": "Review everything before we prepare your custom price.",
    "custom.nav.back": "Back",
    "custom.nav.continue": "Continue",
    "custom.nav.getPrice": "Get my price",
    "custom.validation.designSource":
      "Add a reference image, add a link, or describe the design in the next step before review.",
    "custom.validation.garmentType": "Choose a garment type.",
    "custom.validation.instructions":
      "Tell us enough about the design if you are not adding a reference.",
    "custom.validation.recipientName": "Add the recipient name or label.",
    "custom.validation.measurementRequired": "Required",
    "custom.validation.measurementsConfirmed": "Confirm the measurements before continuing.",
    "custom.validation.firstName": "First name is required.",
    "custom.validation.lastName": "Last name is required.",
    "custom.validation.email": "Enter a valid email address.",
    "custom.validation.submit": "A few details need attention before we can prepare your price.",
    "custom.design.eyebrow": "Your design",
    "custom.design.title": "What would you like us to make?",
    "custom.design.copy": "Start with an idea, a reference, or simply tell us what you're looking for.",
    "custom.design.addPhotos": "Add inspiration photos",
    "custom.design.fileTypes": "JPG, PNG or WEBP",
    "custom.design.choosePhotos": "Choose photos",
    "custom.design.previews": "Selected inspiration photos",
    "custom.design.remove": "Remove",
    "custom.design.linkLabel": "Have a video or post instead?",
    "custom.design.linkPlaceholder": "Instagram, TikTok, Pinterest or other link",
    "custom.details.eyebrow": "Your details",
    "custom.details.title": "Tell us the shape of the garment.",
    "custom.details.copy":
      "Choose the closest category, then add the details that will help us price it thoughtfully.",
    "custom.details.garmentType": "Garment type *",
    "custom.details.color": "Preferred color",
    "custom.details.colorPlaceholder": "White with champagne-gold detailing",
    "custom.details.instructions": "Tell us what you would change or add.",
    "custom.details.instructionsPlaceholder":
      "I like the reference dress, but I want long sleeves, gold detailing and a slightly higher neckline.",
    "custom.details.eventDate": "Do you need it for a specific date?",
    "custom.details.timeline": "This helps us understand your timeline.",
    "custom.garment.womensDress": "Women's Dress",
    "custom.garment.womensTwoPiece": "Women's Two-Piece",
    "custom.garment.mens": "Men's Outfit",
    "custom.garment.children": "Children's Outfit",
    "custom.garment.other": "Other",
    "custom.recipient.eyebrow": "Who is this for?",
    "custom.recipient.title": "Who are we making this for?",
    "custom.recipient.copy":
      "Measurements belong to the person receiving the garment, whether that is you or someone you love.",
    "custom.recipient.name": "Recipient name *",
    "custom.recipient.namePlaceholder": "Mom",
    "custom.recipient.label": "Relationship / label",
    "custom.recipient.labelPlaceholder": "Mother",
    "custom.measurements.eyebrow": "Your measurements",
    "custom.measurements.title": "Let's get the fit right",
    "custom.measurements.copy":
      "Take measurements carefully using our guide. You'll have a chance to review everything before submitting.",
    "custom.measurements.unit": "Measurement unit",
    "custom.measurements.inches": "Inches",
    "custom.measurements.centimeters": "Centimeters",
    "custom.measurements.how": "How to measure",
    "custom.measurements.confirm":
      "I have reviewed these measurements and confirm they are correct for the person receiving this garment.",
    "custom.measurements.videoEyebrow": "Video guide",
    "custom.measurements.videoTitle": "How to measure yourself",
    "custom.measurements.videoCopy": "Watch the guide before entering your measurements.",
    "custom.measurements.watch": "Watch guide",
    "custom.measurements.videoModalCopy":
      "This placeholder is ready for the real Qesem measurement video. It does not autoplay and can be replaced with a local video source later.",
    "custom.measurements.continue": "Continue measuring",
    "custom.measurements.current": "Current guide",
    "custom.measurements.bodyAria": "Interactive measurement body guide",
    "custom.measurements.helpTitle": "How to measure",
    "custom.measurements.gotIt": "Got it",
    "custom.measurements.height": "Height",
    "custom.measurements.bust": "Bust / Chest",
    "custom.measurements.waist": "Waist",
    "custom.measurements.hips": "Hips",
    "custom.measurements.shoulder": "Shoulder width",
    "custom.measurements.sleeve": "Sleeve length",
    "custom.measurements.upperArm": "Upper arm",
    "custom.measurements.garmentLength": "Dress / garment length",
    "custom.measurements.heightHelp":
      "Stand straight without shoes and measure from the top of the head to the floor.",
    "custom.measurements.bustHelp":
      "Wrap the tape around the fullest part of the bust or chest while keeping it level.",
    "custom.measurements.waistHelp":
      "Measure around the natural waistline. Keep the tape comfortably snug, not tight.",
    "custom.measurements.hipsHelp":
      "Measure around the fullest part of the hips with the tape level all the way around.",
    "custom.measurements.shoulderHelp":
      "Measure from the edge of one shoulder to the edge of the other across the back.",
    "custom.measurements.sleeveHelp":
      "Measure from the shoulder point down to where you want the sleeve to end.",
    "custom.measurements.upperArmHelp":
      "Measure around the fullest part of the upper arm without squeezing the tape.",
    "custom.measurements.garmentLengthHelp":
      "Measure from the shoulder down to the point where you want the garment to finish.",
    "custom.measurements.heightMarker": "Measure the full body height in one straight vertical line.",
    "custom.measurements.bustMarker": "Keep the tape flat across the front and around the back.",
    "custom.measurements.waistMarker": "Use the narrowest point of the torso as your guide.",
    "custom.measurements.hipsMarker": "Stand naturally with feet close together.",
    "custom.measurements.shoulderMarker": "Follow a straight shoulder-to-shoulder line.",
    "custom.measurements.sleeveMarker": "Keep the arm relaxed with a soft bend.",
    "custom.measurements.upperArmMarker": "Leave enough ease for comfortable movement.",
    "custom.measurements.garmentLengthMarker":
      "Choose the final hem point before taking this measurement.",
    "custom.contact.eyebrow": "Contact",
    "custom.contact.title": "Where should we send your price?",
    "custom.contact.copy": "We'll send your custom price and a secure link to continue your order.",
    "custom.contact.firstName": "First name *",
    "custom.contact.lastName": "Last name *",
    "custom.contact.email": "Email address *",
    "custom.contact.phone": "Phone number",
    "custom.review.eyebrow": "Review",
    "custom.review.title": "Review your custom design.",
    "custom.review.copy": "Make sure the details are right before we prepare your custom price.",
    "custom.review.design": "Your custom design",
    "custom.review.editDesign": "Edit design",
    "custom.review.referenceLink": "Reference link",
    "custom.review.garmentType": "Garment type",
    "custom.review.color": "Preferred color",
    "custom.review.instructions": "Instructions",
    "custom.review.neededFor": "Needed for",
    "custom.review.notProvided": "Not provided",
    "custom.review.noDate": "No specific date",
    "custom.review.madeFor": "Made for",
    "custom.review.editRecipient": "Edit recipient",
    "custom.review.measurements": "Measurements",
    "custom.review.editMeasurements": "Edit measurements",
    "custom.review.missing": "Missing",
    "custom.review.contact": "Contact",
    "custom.review.editContact": "Edit contact",
    "custom.review.emailMissing": "Email missing",
    "custom.success.eyebrow": "Pricing in progress",
    "custom.success.title": "We've got your design.",
    "custom.success.copyStart": "We're reviewing the details now and will send your custom price to",
    "custom.success.copyEnd": "shortly.",
    "custom.success.ticket": "Custom design",
    "custom.success.status": "Pricing in progress",
    "custom.success.next":
      "Keep an eye on your email. Once your price is ready, you'll receive a secure link to review it and continue to payment.",
    "custom.success.home": "Back to home",
    "custom.success.explore": "Explore our designs",
    "design.selam.category": "Women's Custom Dress",
    "design.selam.alt": "Habesha dress sourced from Ethiopian.store",
    "design.maraki.category": "Embroidered Finish",
    "design.maraki.alt": "Pink and white Habesha dress sourced from Ethiopian.store",
    "design.almaz.category": "Ceremony Set",
    "design.almaz.alt": "White Habesha outfit sourced from Ethiopian.store",
    "design.tsion.category": "Custom Sleeve Work",
    "design.tsion.alt": "Habesha fashion inspiration sourced from Ethiopian.store",
    "design.lidet.category": "Bridal Inspiration",
    "design.lidet.alt": "Traditional Ethiopian clothing inspiration sourced from Ethiopian.store"
  },
  am: {
    "nav.shop": "መደብር",
    "nav.custom": "ብጁ ዲዛይን",
    "nav.story": "ታሪካችን",
    "nav.how": "እንዴት ይሰራል",
    "nav.account": "መለያ",
    "nav.bag": "ቦርሳ",
    "nav.search": "ፍለጋ",
    "nav.openMenu": "ምናሌ ክፈት",
    "nav.closeMenu": "ምናሌ ዝጋ",
    "language.label": "ቋንቋ",
    "language.english": "English",
    "language.amharic": "አማርኛ",
    "hero.aria": "የQesem Habesha Libs መነሻ ገጽ መግቢያ",
    "hero.eyebrow": "ዘመናዊ የሐበሻ ፋሽን፣ በትዕዛዝ የሚሰራ",
    "hero.primary": "ዲዛይኖችን ይመልከቱ",
    "hero.secondary": "የራስዎን ይፍጠሩ",
    "hero.alt": "የዝሆን ጥርስ ቀለም ጥልፍ ያለው ቀሚስ የለበሰች የQesem Habesha Libs ሞዴል",
    "brand.aria": "የQesem Habesha Libs ብራንድ እንቅስቃሴ አሳይ",
    "designs.eyebrow": "ዲዛይኖቻችን",
    "designs.title": "ከዚህ በፊት የሰራናቸው ልብሶች።",
    "designs.viewAll": "ሁሉንም ይመልከቱ",
    "custom.eyebrow": "ብጁ ዲዛይን",
    "custom.title": "በአእምሮዎ ያለውን ዲዛይን ይላኩ።",
    "custom.body":
      "ፎቶ ወይም ቪዲዮ ያጋሩ። ልብሱን፣ የጨርቅ አቅጣጫውን እና አጨራረሱን እንመለከታለን፣ ከዚያም ቀጣዩ ደረጃ ከመጀመሩ በፊት የብጁ ዋጋዎን እንልካለን።",
    "custom.cta": "ዋጋዬን ያግኙ",
    "custom.alt": "ለብጁ የሐበሻ ዲዛይን ስልክ፣ ጨርቅ፣ ጌጥ እና መለኪያ",
    "garment.alt": "ሰው የሌለው የሐበሻ ልብስ የምርት ቅድመ እይታ",
    "garment.hint": "ልብሱን ለማዞር ይጠቁሙ ወይም ይንኩ",
    "process.eyebrow": "እንዴት ይሰራል",
    "process.title": "ከሃሳብ እስከ ልብስ የታሰበ መንገድ።",
    "process.step1": "ዲዛይን ይምረጡ ወይም ይላኩ",
    "process.step2": "የብጁ ዋጋዎን ይቀበሉ",
    "process.step3": "መለኪያዎን ያረጋግጡ",
    "process.step4": "እንሰራዋለን እና እናደርሳለን",
    "craft.eyebrow": "በትኩረት የተሰራ",
    "craft.title": "በኢትዮጵያዊ ባህል የተቀረጸ፣ ለእርስዎ በግል የተሰራ።",
    "craft.alt": "የተጠለፈ የሐበሻ ጨርቅ የሚያስተካክሉ የእጅ ባለሙያ እጆች",
    "measurement.eyebrow": "ፍጹም መጠን",
    "measurement.title": "ከቤት ሆነው እንዴት መለካት እንደሚችሉ በግልጽ እናሳይዎታለን።",
    "measurement.cta": "መመሪያውን ይመልከቱ",
    "measurement.alt": "ለመለኪያ መመሪያ ቅድመ እይታ የተጠቀሰ የተጠለፈ ጨርቅ ቅርብ ዝርዝር",
    "measurement.preview": "የመጠን መመሪያ ቅድመ እይታ",
    "final.eyebrow": "ይጀምሩ",
    "final.line1": "የእርስዎ ዲዛይን።",
    "final.line2": "የእርስዎ መለኪያ።",
    "final.line3": "ለእርስዎ የተሰራ።",
    "footer.tagline": "ባህል፣ በእርስዎ መንገድ።",
    "footer.previous": "የቀድሞ ዲዛይኖች",
    "footer.measurement": "የመለኪያ መመሪያ",
    "footer.shipping": "መላኪያ",
    "footer.returns": "ተመላሽ",
    "footer.faq": "ተደጋጋሚ ጥያቄዎች",
    "footer.contact": "ያግኙን",
    "footer.privacy": "ግላዊነት",
    "footer.terms": "ውሎች",
    "placeholder.comingSoon": "በቅርቡ",
    "placeholder.default": "በቅርቡ",
    "placeholder.body":
      "ይህ መድረሻ ለቀጣዩ ደረጃ ተዘጋጅቷል። ሙሉው ተሞክሮ እየተዘጋጀ ሳለ የመነሻ ገጹ አገናኞች ንቁ ናቸው።",
    "placeholder.return": "ወደ መነሻ ተመለስ",
    "custom.progress.design": "ዲዛይን",
    "custom.progress.details": "ዝርዝር",
    "custom.progress.for": "ለማን",
    "custom.progress.measurements": "መለኪያ",
    "custom.progress.contact": "መገኛ",
    "custom.progress.review": "ግምገማ",
    "custom.progress.aria": "የብጁ ዲዛይን ሂደት",
    "custom.shell.eyebrow": "ብጁ ዲዛይን",
    "custom.visual.0.heading": "ለእርስዎ የተሰራ ነገር ይፍጠሩ።",
    "custom.visual.0.copy":
      "በአእምሮዎ ያለውን ያሳዩን፣ መለኪያዎችን ይስጡን፣ እኛም የብጁ ዋጋዎን በቅርቡ እንልክልዎታለን።",
    "custom.visual.1.heading": "እያንዳንዱ ዝርዝር ጠቃሚ ነው።",
    "custom.visual.1.copy":
      "ቀለም፣ የእጅጌ ቅርጽ፣ የአንገት ቅርጽ፣ አጨራረስ እና የጊዜ ገደብ ሥራውን ለመረዳት ይረዱናል።",
    "custom.visual.2.heading": "ለትክክለኛው ሰው የተሰራ።",
    "custom.visual.2.copy": "ብጁ ልብስ ከገዢው ብቻ ሳይሆን ከሚለብሰው ሰው ይጀምራል።",
    "custom.visual.3.heading": "በመተማመን ይለኩ።",
    "custom.visual.3.copy": "የመመሪያው ምስል መለኪያዎቹን ሲሞሉ የሚለካውን የሰውነት ክፍል ያበራል።",
    "custom.visual.4.heading": "ዋጋውን ለእርስዎ እንልካለን።",
    "custom.visual.4.copy": "በዚህ ደረጃ መለያ፣ የይለፍ ቃል ወይም ክፍያ አያስፈልግም።",
    "custom.visual.5.heading": "የመጨረሻ እይታ።",
    "custom.visual.5.copy": "የብጁ ዋጋዎን ከማዘጋጀታችን በፊት ሁሉንም ይገምግሙ።",
    "custom.nav.back": "ተመለስ",
    "custom.nav.continue": "ቀጥል",
    "custom.nav.getPrice": "ዋጋዬን ያግኙ",
    "custom.validation.designSource":
      "ከግምገማ በፊት የማጣቀሻ ምስል ያክሉ፣ አገናኝ ያክሉ፣ ወይም በቀጣዩ ደረጃ ዲዛይኑን ይግለጹ።",
    "custom.validation.garmentType": "የልብስ አይነት ይምረጡ።",
    "custom.validation.instructions": "ማጣቀሻ ካላከሉ ስለ ዲዛይኑ በቂ መረጃ ይንገሩን።",
    "custom.validation.recipientName": "የተቀባዩን ስም ወይም መለያ ያክሉ።",
    "custom.validation.measurementRequired": "ያስፈልጋል",
    "custom.validation.measurementsConfirmed": "ከመቀጠልዎ በፊት መለኪያዎቹን ያረጋግጡ።",
    "custom.validation.firstName": "የመጀመሪያ ስም ያስፈልጋል።",
    "custom.validation.lastName": "የአባት ስም ያስፈልጋል።",
    "custom.validation.email": "ትክክለኛ የኢሜይል አድራሻ ያስገቡ።",
    "custom.validation.submit": "ዋጋዎን ከማዘጋጀታችን በፊት ጥቂት ዝርዝሮች መስተካከል አለባቸው።",
    "custom.design.eyebrow": "ዲዛይንዎ",
    "custom.design.title": "ምን እንድንሰራልዎ ይፈልጋሉ?",
    "custom.design.copy": "በሃሳብ፣ በማጣቀሻ፣ ወይም በቃላትዎ ብቻ ይጀምሩ።",
    "custom.design.addPhotos": "የመነሻ ፎቶዎችን ያክሉ",
    "custom.design.fileTypes": "JPG, PNG ወይም WEBP",
    "custom.design.choosePhotos": "ፎቶዎች ይምረጡ",
    "custom.design.previews": "የተመረጡ የመነሻ ፎቶዎች",
    "custom.design.remove": "አስወግድ",
    "custom.design.linkLabel": "ቪዲዮ ወይም ፖስት አለዎት?",
    "custom.design.linkPlaceholder": "Instagram, TikTok, Pinterest ወይም ሌላ አገናኝ",
    "custom.details.eyebrow": "ዝርዝሮች",
    "custom.details.title": "የልብሱን ቅርጽ ይንገሩን።",
    "custom.details.copy": "ቅርብ የሆነውን ምድብ ይምረጡ፣ ከዚያም ዋጋውን በጥንቃቄ ለመወሰን የሚረዱንን ዝርዝሮች ያክሉ።",
    "custom.details.garmentType": "የልብስ አይነት *",
    "custom.details.color": "የሚመርጡት ቀለም",
    "custom.details.colorPlaceholder": "ነጭ ከሻምፓኝ-ወርቅ ዝርዝር ጋር",
    "custom.details.instructions": "ምን መቀየር ወይም መጨመር እንደሚፈልጉ ይንገሩን።",
    "custom.details.instructionsPlaceholder": "የማጣቀሻውን ቀሚስ እወዳለሁ፣ ግን ረጅም እጅጌ፣ የወርቅ ዝርዝር እና ትንሽ ከፍ ያለ አንገት እፈልጋለሁ።",
    "custom.details.eventDate": "ለተወሰነ ቀን ያስፈልግዎታል?",
    "custom.details.timeline": "ይህ የጊዜ መስመርዎን ለመረዳት ይረዳናል።",
    "custom.garment.womensDress": "የሴቶች ቀሚስ",
    "custom.garment.womensTwoPiece": "የሴቶች ሁለት-ክፍል",
    "custom.garment.mens": "የወንዶች ልብስ",
    "custom.garment.children": "የልጆች ልብስ",
    "custom.garment.other": "ሌላ",
    "custom.recipient.eyebrow": "ለማን ነው?",
    "custom.recipient.title": "ይህን ለማን እንሰራለን?",
    "custom.recipient.copy": "መለኪያዎቹ ልብሱን ለሚቀበለው ሰው ናቸው፣ እርስዎም ይሁኑ ወይም የሚወዱት ሰው።",
    "custom.recipient.name": "የተቀባይ ስም *",
    "custom.recipient.namePlaceholder": "እናቴ",
    "custom.recipient.label": "ዝምድና / መለያ",
    "custom.recipient.labelPlaceholder": "እናት",
    "custom.measurements.eyebrow": "መለኪያዎች",
    "custom.measurements.title": "መጠኑን ትክክል እናድርግ",
    "custom.measurements.copy": "መመሪያችንን በመጠቀም መለኪያዎችን በጥንቃቄ ይውሰዱ። ከመላክዎ በፊት ሁሉንም የመገምገም እድል ይኖርዎታል።",
    "custom.measurements.unit": "የመለኪያ ክፍል",
    "custom.measurements.inches": "ኢንች",
    "custom.measurements.centimeters": "ሴንቲሜትር",
    "custom.measurements.how": "እንዴት እንደሚለኩ",
    "custom.measurements.confirm": "እነዚህን መለኪያዎች ገምግሜ ለልብሱ ተቀባይ ትክክል መሆናቸውን አረጋግጣለሁ።",
    "custom.measurements.videoEyebrow": "የቪዲዮ መመሪያ",
    "custom.measurements.videoTitle": "ራስዎን እንዴት መለካት እንደሚችሉ",
    "custom.measurements.videoCopy": "መለኪያዎችን ከማስገባትዎ በፊት መመሪያውን ይመልከቱ።",
    "custom.measurements.watch": "መመሪያውን ይመልከቱ",
    "custom.measurements.videoModalCopy": "ይህ ቦታ ለእውነተኛው የQesem መለኪያ ቪዲዮ ዝግጁ ነው። በራሱ አይጫወትም እና በኋላ በአካባቢያዊ ቪዲዮ ምንጭ መተካት ይቻላል።",
    "custom.measurements.continue": "መለካት ቀጥል",
    "custom.measurements.current": "አሁን ያለው መመሪያ",
    "custom.measurements.bodyAria": "ተግባራዊ የሰውነት መለኪያ መመሪያ",
    "custom.measurements.helpTitle": "እንዴት እንደሚለኩ",
    "custom.measurements.gotIt": "ተረዳሁ",
    "custom.measurements.height": "ቁመት",
    "custom.measurements.bust": "ደረት",
    "custom.measurements.waist": "ወገብ",
    "custom.measurements.hips": "ዳሌ",
    "custom.measurements.shoulder": "የትከሻ ስፋት",
    "custom.measurements.sleeve": "የእጅጌ ርዝመት",
    "custom.measurements.upperArm": "የላይኛው ክንድ",
    "custom.measurements.garmentLength": "የቀሚስ / ልብስ ርዝመት",
    "custom.measurements.heightHelp": "ጫማ ሳይለብሱ ቀጥ ብለው ቆመው ከራስ ጫፍ እስከ ወለል ይለኩ።",
    "custom.measurements.bustHelp": "መለኪያውን በደረት ሙሉ ክፍል ዙሪያ ያዙሩት፣ ቀጥ እንዲሆን ያድርጉ።",
    "custom.measurements.waistHelp": "በተፈጥሯዊ የወገብ መስመር ዙሪያ ይለኩ። መለኪያው በምቾት ይጠበቅ፣ አይጨነቅ።",
    "custom.measurements.hipsHelp": "በዳሌ ሙሉ ክፍል ዙሪያ መለኪያውን ቀጥ አድርገው ይለኩ።",
    "custom.measurements.shoulderHelp": "ከአንዱ ትከሻ ጫፍ እስከ ሌላው ትከሻ ጫፍ በጀርባ በኩል ይለኩ።",
    "custom.measurements.sleeveHelp": "ከትከሻ ነጥብ እስከ እጅጌው እንዲያበቃበት የሚፈልጉት ቦታ ይለኩ።",
    "custom.measurements.upperArmHelp": "መለኪያውን ሳይጨንቁ በላይኛው ክንድ ሙሉ ክፍል ዙሪያ ይለኩ።",
    "custom.measurements.garmentLengthHelp": "ከትከሻ ወደ ታች ልብሱ እንዲያበቃበት የሚፈልጉት ቦታ ድረስ ይለኩ።",
    "custom.measurements.heightMarker": "ሙሉ ቁመትን በአንድ ቀጥ ያለ መስመር ይለኩ።",
    "custom.measurements.bustMarker": "መለኪያውን በፊትና በጀርባ ጠፍጣፋ ያድርጉ።",
    "custom.measurements.waistMarker": "የሰውነት በጣም ጠባብ ክፍልን መመሪያ ያድርጉ።",
    "custom.measurements.hipsMarker": "እግሮችዎን ቅርብ አድርገው በተፈጥሮ ይቁሙ።",
    "custom.measurements.shoulderMarker": "ቀጥ ያለ ከትከሻ እስከ ትከሻ መስመር ይከተሉ።",
    "custom.measurements.sleeveMarker": "ክንዱን በቀላል ማጠፍ ዘና አድርገው ይያዙ።",
    "custom.measurements.upperArmMarker": "ለምቾት እንቅስቃሴ በቂ ቦታ ይተዉ።",
    "custom.measurements.garmentLengthMarker": "ይህን መለኪያ ከመውሰድዎ በፊት የመጨረሻውን የጫፍ ቦታ ይምረጡ።",
    "custom.contact.eyebrow": "መገኛ",
    "custom.contact.title": "ዋጋዎን ወዴት እንላክ?",
    "custom.contact.copy": "የብጁ ዋጋዎን እና ትዕዛዝዎን ለመቀጠል የሚያስችል ደህንነቱ የተጠበቀ አገናኝ እንልካለን።",
    "custom.contact.firstName": "የመጀመሪያ ስም *",
    "custom.contact.lastName": "የአባት ስም *",
    "custom.contact.email": "የኢሜይል አድራሻ *",
    "custom.contact.phone": "ስልክ ቁጥር",
    "custom.review.eyebrow": "ግምገማ",
    "custom.review.title": "የብጁ ዲዛይንዎን ይገምግሙ።",
    "custom.review.copy": "የብጁ ዋጋዎን ከማዘጋጀታችን በፊት ዝርዝሮቹ ትክክል መሆናቸውን ያረጋግጡ።",
    "custom.review.design": "የብጁ ዲዛይንዎ",
    "custom.review.editDesign": "ዲዛይን አስተካክል",
    "custom.review.referenceLink": "የማጣቀሻ አገናኝ",
    "custom.review.garmentType": "የልብስ አይነት",
    "custom.review.color": "የሚመርጡት ቀለም",
    "custom.review.instructions": "መመሪያዎች",
    "custom.review.neededFor": "የሚያስፈልግበት ቀን",
    "custom.review.notProvided": "አልተሰጠም",
    "custom.review.noDate": "የተወሰነ ቀን የለም",
    "custom.review.madeFor": "ለማን የተሰራ",
    "custom.review.editRecipient": "ተቀባይ አስተካክል",
    "custom.review.measurements": "መለኪያዎች",
    "custom.review.editMeasurements": "መለኪያዎችን አስተካክል",
    "custom.review.missing": "ጎድሏል",
    "custom.review.contact": "መገኛ",
    "custom.review.editContact": "መገኛ አስተካክል",
    "custom.review.emailMissing": "ኢሜይል ጎድሏል",
    "custom.success.eyebrow": "ዋጋ በመዘጋጀት ላይ",
    "custom.success.title": "ዲዛይንዎን ተቀብለናል።",
    "custom.success.copyStart": "ዝርዝሮቹን እየገመገምን ነው፣ የብጁ ዋጋዎንም ወደ",
    "custom.success.copyEnd": "በቅርቡ እንልካለን።",
    "custom.success.ticket": "ብጁ ዲዛይን",
    "custom.success.status": "ዋጋ በመዘጋጀት ላይ",
    "custom.success.next": "ኢሜይልዎን ይከታተሉ። ዋጋዎ ሲዘጋጅ፣ ለመገምገም እና ወደ ክፍያ ለመቀጠል ደህንነቱ የተጠበቀ አገናኝ ይደርስዎታል።",
    "custom.success.home": "ወደ መነሻ ተመለስ",
    "custom.success.explore": "ዲዛይኖቻችንን ይመልከቱ",
    "design.selam.category": "የሴቶች ብጁ ቀሚስ",
    "design.selam.alt": "ከEthiopian.store የተወሰደ የሐበሻ ቀሚስ",
    "design.maraki.category": "የጥልፍ አጨራረስ",
    "design.maraki.alt": "ከEthiopian.store የተወሰደ ሮዝ እና ነጭ የሐበሻ ቀሚስ",
    "design.almaz.category": "የሥነ ሥርዓት ስብስብ",
    "design.almaz.alt": "ከEthiopian.store የተወሰደ ነጭ የሐበሻ ልብስ",
    "design.tsion.category": "ብጁ የእጅጌ ሥራ",
    "design.tsion.alt": "ከEthiopian.store የተወሰደ የሐበሻ ፋሽን አነሳሽነት",
    "design.lidet.category": "የሙሽራ አነሳሽነት",
    "design.lidet.alt": "ከEthiopian.store የተወሰደ የባህላዊ ኢትዮጵያ ልብስ አነሳሽነት"
  }
} satisfies Record<Language, Record<string, string>>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem(storageKey);
    if (saved === "am" || saved === "en") {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = useCallback((nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    window.localStorage.setItem(storageKey, nextLanguage);
  }, []);

  useEffect(() => {
    document.documentElement.lang = language === "am" ? "am" : "en";
  }, [language]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      t: (key) => dictionary[language][key] ?? dictionary.en[key]
    }),
    [language, setLanguage]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }

  return context;
}
